---
- name: prelude
  hosts: all
  environment: "{{ os_admin }}"
  tags:
    - prelude
    - part_a
  tasks:
    #- WIP
    #- name: notify users
    #  include_role:
    #    name: hvmnd
    #  vars:
    #    hivemind_hosts: "{{ ansible_play_batch }}"
    #  run_once: true
    #  tags: comms
    - name: stop and lock vms
      include_role:
        name: cloudman
      with_items:
        - hype_list
        - hype_stop
        - hype_lock
      loop_control:
        loop_var: role_action
    - name: stop puppet
      become: yes
      command: /opt/puppetlabs/bin/puppet agent --disable "bionic upgrade"
    - name: stop nova-compute
      become: yes
      systemd:
        name: nova-compute
        state: stopped

- name: hypervisor xenial pre drl
  hosts: all
  tags:
    - pre-drl
    - part_a
  environment: "{{ proxy_env }}"
  tasks:
    - name: remove i386 arch, purge prefs
      include_role:
        name: pacman
      with_items:
        - remove_arch
        - purge_prefs
      loop_control:
        loop_var: role_action
      vars:
        arch: i386
    - name: cleanup old sources
      include_role:
        name: pacman
      with_items:
        - purge_sources
      loop_control:
        loop_var: role_action
      vars:
        old_source:
          - "dell"
          - "linux.dell.com.sources"
          - "midonet"
          - "midonet-openstack-integration"
          - "midonet-third-party"
          - "nectar-mitaka"
          - "nectar-newton"
          - "nectar-ocata"
          - "nectar-pike"
          - "openjdk-ppa"
          - "puppetlabs_pc1"
          - "qemu-libvirt-repo"
          - "ubuntu-cloud-archive"
    - name: pre-do-release dist upgrade
      include_role:
        name: pacman
      vars:
        role_action: patch_seq
    #-- bchache antics...

- name: hypervisor xenial drl bionic
  hosts: all
  tags: drl
  environment: "{{ proxy_env }}"
  tasks:
    - name: drl
      include_role:
        name: drl

- name: hypervisor bionic post drl
  hosts: all
  environment: "{{ proxy_env }}"
  tags:
    - post-drl
    - part_b
  tasks:
    - name: gather bionic facts
      setup:
    - name: Update mlnx
      # will uninstall nova compute if it runs
      # requires bionc repos
      include_role:
        name: firmware
      vars:
        role_action: mlnx
      when:
        - ansible_p1p1 is defined
        - ansible_p1p1.module is search('mlx')
    - name: Update firmware
      include_role:
        name: firmware
      with_items:
        - install
        - update
      loop_control:
        loop_var: role_action
      when: ansible_virtualization_role == 'host'
      tags: dell_firmware

    - name: flush handlers
      meta: flush_handlers

    - name: cleanup xenial sources
      include_role:
        name: pacman
      with_items:
        - purge_sources
      loop_control:
        loop_var: role_action
      vars:
        release: xenial

    - name: routine node config and update puppet
      include_role:
        name: baremetal
      with_items:
        - pre_config
        - reinstall
      loop_control:
        loop_var: role_action

    #-- move into drl role-action
    - name: enable puppet
      become: yes
      command: /opt/puppetlabs/bin/puppet agent --enable

    - name: run puppet to get bionic repos
      become: yes
      puppet:
      register: puppet_run_result
      ignore_errors: yes

    - name: start midolman
      become: yes
      systemd:
        name: midolman
        state: started
      when: "Could not find init script for 'midolman' in puppet_run_result.stderr"

    - name: post-do-release dist upgrade
      include_role:
        name: pacman
      vars:
        role_action: patch_seq
      when: "Execution of '/usr/bin/apt-get in puppet_run_result.stderr"

    #-- bcache antics...

- name: postlude
  hosts: all
  environment: "{{ os_admin }}"
  tags:
    - postlude
    - part_b
  tasks:
    - name: system checks
      include_role:
        name: baremetal
      vars:
        role_action: check
        node_type: 'hypervisor'

    - name: Test "{{ ansible_play_batch }}"
      jenkins_build:
        name: "tempest-compute-host-check"
        args:
          CLOUD: "production"
          AVAILABILITY_ZONE: "{{ cell_name }}"
          HOST: "{{ item }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_server }}"
      loop: "{{ ansible_play_batch }}"
      run_once: true
      tags: tempest
      delegate_to: localhost

    - name: start and unlock vms
      include_role:
        name: cloudman
      with_items:
        - hype_unlock
        - hype_start
      loop_control:
        loop_var: role_action
