---
- name: get a list of installed kernels
  find:
    paths: /boot/
    patterns: "initrd.img-*"
  register: initrd

- set_fact: initrd_paths="{{ initrd.files | map(attribute='path') | list }}" # noqa 502
- set_fact: initrd_files="{{ initrd_paths | map('basename') | list }}" # noqa 502
- set_fact: old_initrd_files="{{ initrd_files | map('regex_search', '^.*\\.old-dkms$') | list + [ansible_kernel] }}" # noqa 502
- set_fact: obsolete_kernels="{{ initrd_files | difference(old_initrd_files) | map('regex_replace', 'initrd\\.img-','') | list }}" # noqa 502


- name: removed old initrd_files
  become: yes
  command: update-initrd -d -k  "{{ item }}"
  loop: "{{ obsolete_kernels }}"
  ignore_errors: yes
  register: return

- debug:
    var: return

- name: purge old kernels
  become: yes
  apt:
    name: linux-image-"{{ item }}"
    state: absent
    purge: yes
  loop: "{{ obsolete_kernels }}"
