- name: check & install update-manager-core
  become: yes
  block:
    - name: check if update-manager-core is installed
      command: dpkg -l update-manager-core

  rescue:
    - name: install update-manager-core
      apt:
        name: update-manager-core
        state: latest

- name: system checks
  include: system_check.yml

- name: stat target
  stat:
    path: /var/run/reboot-required
  register: stat_result

- name: reboot if required
  become: yes
  reboot:
    reboot_timeout: 1800
  when: stat_result.stat.exists
