---

- name: do-release-upgrade # noqa 301 305
  shell: do-release-upgrade -f DistUpgradeViewNonInteractive
  async: 2700
  poll: 0
  register: drl_task

- name: see drl_task
  debug:
    var: drl_task

- name: Delay before checking pid
  pause:
    prompt: Delay before checking pid
    seconds: 270

- name: check
  include_tasks: check.yml
  until: drl_status.finished
  register: pid

#- name: check if do-release is still running
#  command: ps -C do-release-upgrade
#  register: ps

#- name: Wait for reboot
#  wait_for:
#    port: 22
#    host: '{{ inventory_hostname }}-1g.erc.monash.edu.au'
#    search_regex: OpenSSH
#    delay: 300
#    connect_timeout: 30
#  delegate_to: ra2
#  tags: drl

- name: reboot
  reboot:
    reboot_timeout: 1800
  when: ps.stdout is not defined
