---

- name: do-release-upgrade # noqa 301 305
  shell: nohup do-release-upgrade -f DistUpgradeViewNonInteractive </dev/null
#  async: 2700
#  poll: 0
  register: drl_task

- name: reboot
  become: yes
  reboot:
    reboot_timeout: 1800
