---
- name: refresh facts
  setup:

- name: check boot space
  assert:
    that:
      - item.size_available > 100000000
  with_items: "{{ ansible_mounts }}"
  when: item.mount == '/boot'
  register: assertion
  ignore_errors: yes

- name: fix boot part
  include_tasks: boot_part_fix.yml
  when:
    - assertion.failed is defined
    - assertion.failed

- name: check boot space again
  assert:
    that:
      - item.size_available > 100000000
  with_items: "{{ ansible_mounts }}"
  register: assertion
  when:
    - item.mount == '/boot'
    - assertion.failed is defined
    - assertion.failed
