---
# handlers file for roles/baremetal
- name: run puppet
  become: true
  puppet:

- name: update grub
  become: true
  command: update-grub

#- name: reboot baremetal
#  become: true
#  reboot:
#    reboot_timeout: 1800
