---
# handlers file for roles/bioscfg

# requires ansible 2.8
#- name: Create bios config job
#  idrac_redfish_command:
#    category: Systems
#    command: CreateBiosConfigJob
#    baseuri: "{{ redfish.baseuri }}"
#    username: "{{ redfish.user }}"
#    password: "{{ redfish.password }}"

- name: Create bios config job
  delegate_to: "{{ redfish.oob_bastion }}"
  shell: |
    curl https://{{ redfish.baseuri }}/redfish/v1/Managers/iDRAC.Embedded.1/Jobs \
    --noproxy '*' \
    -k -s -u {{ redfish.user }}:{{ redfish.password }} \
    -H "Content-Type: application/json" \
    -d '{"TargetSettingsURI":"/redfish/v1/Systems/System.Embedded.1/Bios/Settings"}'
