---
- name: Gather_facts
  setup:

- name: Autoremove if uptime is gt 24 hours
  become: true
  apt:
    autoremove:
  when: ansible_uptime_seconds > 86400

- name: Upgrade all packages to the latest version
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    update_cache: yes
    upgrade: dist
    dpkg_options: 'force-confold,force-confdef'
