---
- name: Remove architecture
  block:
    - name: purge "{{ arch }}" packages
      apt:
        name: "*.*:{{ arch }}"
        purge: yes
    - name: remove "{{ arch }}" architecture
      command: "dpkg --remove-architecture {{ arch }}"
    - name: apt cleanup
      apt:
        autoremove: yes
