---
- name: get bios attributes
  redfish_facts:
    category: Systems
    command: GetBiosAttributes
    baseuri: "{{ redfish.baseuri }}"
    user: "{{ redfish.user }}"
    password: "{{ redfish.password }}"
  register: result
  delegate_to: "{{ redfish.oob_bastion }}"
