---

#reboot module new in ansible 2.7
- name: firmware reboot
  become: yes
  reboot:
    reboot_timeout: 3600

- name: install nova-compute
  become: yes
  apt:
    name: nova-compute
    state: present
