---
- name: Sync repo to dev site
  synchronize:
    src: "{{ repo_location }}"
    dest: /etc/puppetlabs/code/dev_environments/dev_${USER}
    delete: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git*"
