---
# Equivalent of puppet agent -t --environment dev_$USER --server r10k.rc.nectar.org.au --no-use_srv_records
- name: run puppet
  puppet:
    # an *elegent* hack to get user because we don't use sudo properly
    environment: dev_{{ ansible_env['PWD'] | basename }}
    puppetmaster: r10k.rc.nectar.org.au
    use_srv_records: False
    show_diff: True
